[package]
name = "r7-rs"
version = "0.1.0"
authors = ["Mike MacDonald (crazymykl) <crazymykl@gmail.com>"]

[lib]
name = "r7rs"

[dependencies]
peg = "0.5.3"
peg-syntax-ext = "0.5.0"
num = "0.1.0"
rustyline = "1.0.0"

[features]
default = []
show_ast = []
