[package]
name = "r7-rs"
version = "0.1.0"
authors = ["Mike MacDonald (crazymykl) <crazymykl@gmail.com>"]

[lib]
name = "r7rs"

[dependencies]
peg = "0.3.8"
num = "0.1.0"
rustyline = "0.2.0"

[features]
default = []
show_ast = []
